//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:19:59 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Korisnik}Korisnik"/>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Smestaj}SJedinica"/>
 *         &lt;element name="Odobren" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "korisnik",
    "sJedinica",
    "odobren",
    "tekst"
})
@XmlRootElement(name = "Komentar", namespace = "https://github.com/Shekrba/MegaTravel/Komentar")
public class Komentar {

    @XmlElement(name = "Korisnik", namespace = "https://github.com/Shekrba/MegaTravel/Korisnik", required = true)
    protected TKorisnik korisnik;
    @XmlElement(name = "SJedinica", required = true)
    protected SJedinica sJedinica;
    @XmlElement(name = "Odobren", namespace = "https://github.com/Shekrba/MegaTravel/Komentar", defaultValue = "false")
    protected boolean odobren;
    @XmlElement(name = "Tekst", namespace = "https://github.com/Shekrba/MegaTravel/Komentar", required = true)
    protected String tekst;

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link TKorisnik }
     *     
     */
    public TKorisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKorisnik }
     *     
     */
    public void setKorisnik(TKorisnik value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the sJedinica property.
     * 
     * @return
     *     possible object is
     *     {@link SJedinica }
     *     
     */
    public SJedinica getSJedinica() {
        return sJedinica;
    }

    /**
     * Sets the value of the sJedinica property.
     * 
     * @param value
     *     allowed object is
     *     {@link SJedinica }
     *     
     */
    public void setSJedinica(SJedinica value) {
        this.sJedinica = value;
    }

    /**
     * Gets the value of the odobren property.
     * 
     */
    public boolean isOdobren() {
        return odobren;
    }

    /**
     * Sets the value of the odobren property.
     * 
     */
    public void setOdobren(boolean value) {
        this.odobren = value;
    }

    /**
     * Gets the value of the tekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekst() {
        return tekst;
    }

    /**
     * Sets the value of the tekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekst(String value) {
        this.tekst = value;
    }

}
