//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:20:19 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Korisnik}Korisnik"/>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Smestaj}SJedinica"/>
 *         &lt;element name="Vrednost">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "korisnik",
    "sJedinica",
    "vrednost"
})
@XmlRootElement(name = "Ocena", namespace = "https://github.com/Shekrba/MegaTravel/Ocena")
public class Ocena {

    @XmlElement(name = "Korisnik", namespace = "https://github.com/Shekrba/MegaTravel/Korisnik", required = true)
    protected TKorisnik korisnik;
    @XmlElement(name = "SJedinica", required = true)
    protected SJedinica sJedinica;
    @XmlElement(name = "Vrednost", namespace = "https://github.com/Shekrba/MegaTravel/Ocena")
    protected int vrednost;

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link TKorisnik }
     *     
     */
    public TKorisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKorisnik }
     *     
     */
    public void setKorisnik(TKorisnik value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the sJedinica property.
     * 
     * @return
     *     possible object is
     *     {@link SJedinica }
     *     
     */
    public SJedinica getSJedinica() {
        return sJedinica;
    }

    /**
     * Sets the value of the sJedinica property.
     * 
     * @param value
     *     allowed object is
     *     {@link SJedinica }
     *     
     */
    public void setSJedinica(SJedinica value) {
        this.sJedinica = value;
    }

    /**
     * Gets the value of the vrednost property.
     * 
     */
    public int getVrednost() {
        return vrednost;
    }

    /**
     * Sets the value of the vrednost property.
     * 
     */
    public void setVrednost(int value) {
        this.vrednost = value;
    }

}
