//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:21:04 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/Shekrba/MegaTravel/Smestaj", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model;
