//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:20:55 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Smestaj}SJedinica"/>
 *         &lt;element name="DatumRez" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Od" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Do" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="UCena" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Korisnik}Korisnik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sJedinica",
    "datumRez",
    "od",
    "_do",
    "uCena",
    "korisnik"
})
@XmlRootElement(name = "Rezervacija", namespace = "https://github.com/Shekrba/MegaTravel")
public class Rezervacija {

    @XmlElement(name = "SJedinica", required = true)
    protected SJedinica sJedinica;
    @XmlElement(name = "DatumRez", namespace = "https://github.com/Shekrba/MegaTravel", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRez;
    @XmlElement(name = "Od", namespace = "https://github.com/Shekrba/MegaTravel", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar od;
    @XmlElement(name = "Do", namespace = "https://github.com/Shekrba/MegaTravel", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar _do;
    @XmlElement(name = "UCena", namespace = "https://github.com/Shekrba/MegaTravel")
    protected int uCena;
    @XmlElement(name = "Korisnik", namespace = "https://github.com/Shekrba/MegaTravel/Korisnik", required = true)
    protected TKorisnik korisnik;

    /**
     * Gets the value of the sJedinica property.
     * 
     * @return
     *     possible object is
     *     {@link SJedinica }
     *     
     */
    public SJedinica getSJedinica() {
        return sJedinica;
    }

    /**
     * Sets the value of the sJedinica property.
     * 
     * @param value
     *     allowed object is
     *     {@link SJedinica }
     *     
     */
    public void setSJedinica(SJedinica value) {
        this.sJedinica = value;
    }

    /**
     * Gets the value of the datumRez property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRez() {
        return datumRez;
    }

    /**
     * Sets the value of the datumRez property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRez(XMLGregorianCalendar value) {
        this.datumRez = value;
    }

    /**
     * Gets the value of the od property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOd() {
        return od;
    }

    /**
     * Sets the value of the od property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOd(XMLGregorianCalendar value) {
        this.od = value;
    }

    /**
     * Gets the value of the do property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDo() {
        return _do;
    }

    /**
     * Sets the value of the do property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDo(XMLGregorianCalendar value) {
        this._do = value;
    }

    /**
     * Gets the value of the uCena property.
     * 
     */
    public int getUCena() {
        return uCena;
    }

    /**
     * Sets the value of the uCena property.
     * 
     */
    public void setUCena(int value) {
        this.uCena = value;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link TKorisnik }
     *     
     */
    public TKorisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKorisnik }
     *     
     */
    public void setKorisnik(TKorisnik value) {
        this.korisnik = value;
    }

}
