package com.megatravel.agentservice.model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.23 at 02:20:55 PM CEST
//



import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDate;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Smestaj}SJedinica"/>
 *         &lt;element name="DatumRez" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Od" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element ref="{https://github.com/Shekrba/MegaTravel/Korisnik}Korisnik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "sJedinica",
        "datumRez",
        "od",
        "korisnik"
})
@XmlRootElement(name = "Rezervacija", namespace = "https://github.com/Shekrba/MegaTravel")
@Entity
public class Rezervacija {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    @XmlElement(name = "SJedinica", required = true)
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    protected SJedinica sJedinica;

    @XmlElement(name = "DatumRez", namespace = "https://github.com/Shekrba/MegaTravel", required = true)
    @XmlSchemaType(name = "date")
    @Column(name = "datumRez", unique = false, nullable = false)
    protected LocalDate datumRez;

    @XmlElement(name = "Od", namespace = "https://github.com/Shekrba/MegaTravel", required = true)
    @XmlSchemaType(name = "date")
    @Column(name = "od", unique = false, nullable = false)
    protected LocalDate od;

    @XmlElement(name = "Do", namespace = "https://github.com/Shekrba/MegaTravel", required = true)
    @XmlSchemaType(name = "date")
    @Column(name = "do", unique = false, nullable = false)
    protected LocalDate _do;

    @XmlElement(name = "UCena", namespace = "https://github.com/Shekrba/MegaTravel")
    @Column(name = "ukupnaCena", unique = false, nullable = false)
    protected int uCena;

    @XmlElement(name = "Korisnik", namespace = "https://github.com/Shekrba/MegaTravel/Korisnik", required = true)
    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    protected TKorisnik korisnik;

    @XmlElement(name = "StatusRezervacije", required = true, defaultValue = "rezervisano")
    @XmlSchemaType(name = "string")
    @Column(name = "status", unique = false, nullable = false)
    protected StatusRezervacije statusRezervacije;

    public void setStatusRezervacije(StatusRezervacije statusRezervacije) {
        this.statusRezervacije = statusRezervacije;
    }

    public StatusRezervacije getStatusRezervacije() {
        return statusRezervacije;
    }

    public void setDatumRez(LocalDate datumRez) {
        this.datumRez = datumRez;
    }

    public void setOd(LocalDate od) {
        this.od = od;
    }

    public void setKorisnik(TKorisnik korisnik) {
        this.korisnik = korisnik;
    }

    public LocalDate getDatumRez() {
        return datumRez;
    }

    public LocalDate getOd() {
        return od;
    }

    public TKorisnik getKorisnik() {
        return korisnik;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SJedinica getsJedinica() {
        return sJedinica;
    }

    public void setsJedinica(SJedinica sJedinica) {
        this.sJedinica = sJedinica;
    }

    public LocalDate get_do() {
        return _do;
    }

    public void set_do(LocalDate _do) {
        this._do = _do;
    }

    public int getuCena() {
        return uCena;
    }

    public void setuCena(int uCena) {
        this.uCena = uCena;
    }



}
