version: '3'
services:

  mysql-standalone:
    image: mysql:5.6
    container_name: mysql-standalone
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: megatravel
      MYSQL_USER: root

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - mysql-standalone
    links:
      - mysql-standalone:mysql-standalone

  zuul:
    image: zuul
    container_name: zuul
    build:
      context: ./zuul
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    depends_on:
      - discovery-server
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server

  login:
    image: login
    container_name: login
    build:
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - zuul
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server
      - zuul:zuul

  search:
    image: search
    container_name: search
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - zuul
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server
      - zuul:zuul