version: '3'
services:

  mysql-standalone:
    image: mysql:5.6
    container_name: mysql-standalone
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: megatravel
      MYSQL_USER: root

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    links:
      - mysql-standalone:mysql-standalone

  zuul:
    image: zuul
    container_name: zuul
    build:
      context: ./zuul
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server

  search:
    image: search
    container_name: search
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server
      - zuul:zuul

  login:
    image: login
    container_name: login
    build:
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server
      - zuul:zuul



  rezervacija:
    image: rezervacija
    container_name: rezervacija
    build:
      context: ./rezervacija
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server
      - zuul:zuul

  admin:
    image: admin
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server
      - zuul:zuul

  agent:
    image: agent
    container_name: agent
    build:
      context: ./agent-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    links:
      - mysql-standalone:mysql-standalone
      - discovery-server:discovery-server
      - zuul:zuul