//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.23 at 02:21:04 PM CEST
//

package com.megatravel.agentback.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusPoruke.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatusPoruke">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="neodgovoreno"/>
 *     &lt;enumeration value="odgovoreno"/>
 *     &lt;enumeration value="odgovor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "StatusPoruke")
@XmlEnum
public enum StatusPoruke {

    @XmlEnumValue("neodgovoreno")
    NEODGOVORENO("neodgovoreno"),
    @XmlEnumValue("otkazano")
    ODGOVORENO("odgovoreno"),
    @XmlEnumValue("odgovor")
    ODGOVOR("odgovor");
    private final String value;

    StatusPoruke(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusPoruke fromValue(String v) {
        for (StatusPoruke c: StatusPoruke.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}