//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:21:04 PM CEST 
//


package com.megatravel.agent.model;

import com.megatravel.agent.xml.dto.SJedinicaXMLDTO;

import javax.persistence.*;
import javax.xml.bind.annotation.*;



@Entity
public class SJedinica {


    @Column(name = "cena", unique = false, nullable = false)
    private double cena;


    @Column(name = "brojKreveta", unique = false, nullable = false)
    private int brojKreveta;


    @Column(name = "dostupnost", unique = false, nullable = false)
    private Boolean dostupnost;


    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Smestaj smestaj;

    @Column(name = "broj", unique = false, nullable = false)
    private int broj;




    public double getCena() {
        return cena;
    }


    public void setCena(double value) {
        this.cena = value;
    }


    public int getBrojKreveta() {
        return brojKreveta;
    }


    public void setBrojKreveta(int value) {
        this.brojKreveta = value;
    }


    public boolean isDostupnost() {
        return dostupnost;
    }


    public void setDostupnost(boolean value) {
        this.dostupnost = value;
    }


    public Long getId() {
        return id;
    }


    public void setId(Long value) {
        this.id = value;
    }

    public SJedinica(SJedinicaXMLDTO sjXML){
        this.broj=sjXML.getBroj();
        this.brojKreveta=sjXML.getBrojKreveta();
        this.cena=sjXML.getCena();
        this.dostupnost=sjXML.getDostupnost();
        this.id=sjXML.getId();
    }

}
