//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:20:55 PM CEST 
//


package com.megatravel.search.model;

import javax.persistence.*;
import java.util.Date;

@Entity
public class Rezervacija {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    protected Long id;

    @ManyToOne(fetch = FetchType.EAGER)
    protected SJedinica sJedinica;

    @Column(name = "datumRez", unique = false, nullable = false)
    protected Date datumRez;

    @Column(name = "od", unique = false, nullable = false)
    protected Date od;

    @Column(name = "do", unique = false, nullable = false)
    protected Date _do;

    @Column(name = "ukupnaCena", unique = false, nullable = false)
    protected double uCena;

    @ManyToOne(fetch = FetchType.EAGER)
    protected User korisnik;

    @Column(name = "canBeRated", unique = false, nullable = false)
    protected boolean canBeRated;

    @Column(name = "rated", unique = false, nullable = false)
    protected boolean rated;

    @Column(name = "canceled", unique = false, nullable = false,columnDefinition="boolean default false")
    protected boolean canceled = false;

    public boolean isCanceled() {
        return canceled;
    }

    public void setCanceled(boolean canceled) {
        this.canceled = canceled;
    }

    public boolean isRated() {
        return rated;
    }

    public void setRated(boolean rated) {
        this.rated = rated;
    }

    public boolean isCanBeRated() {
        return canBeRated;
    }

    public void setCanBeRated(boolean canBeRated) {
        this.canBeRated = canBeRated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SJedinica getsJedinica() {
        return sJedinica;
    }

    public void setsJedinica(SJedinica sJedinica) {
        this.sJedinica = sJedinica;
    }

    public Date get_do() {
        return _do;
    }

    public void set_do(Date _do) {
        this._do = _do;
    }

    public double getuCena() {
        return uCena;
    }

    public void setuCena(double uCena) {
        this.uCena = uCena;
    }

    public SJedinica getSJedinica() {
        return sJedinica;
    }

    public void setSJedinica(SJedinica value) {
        this.sJedinica = value;
    }

    public Date getDatumRez() {
        return datumRez;
    }

    public void setDatumRez(Date value) {
        this.datumRez = value;
    }

    public Date getOd() {
        return od;
    }

    public void setOd(Date value) {
        this.od = value;
    }

    public Date getDo() {
        return _do;
    }

    public void setDo(Date value) {
        this._do = value;
    }

    public double getUCena() {
        return uCena;
    }

    public void setUCena(double value) {
        this.uCena = value;
    }

    public User getKorisnik() {
        return korisnik;
    }

    public void setKorisnik(User korisnik) {
        this.korisnik = korisnik;
    }
}
