//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 02:21:04 PM CEST 
//


package com.megatravel.admin.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
public class Usluga {

    @Column(name = "naziv", unique = false, nullable = false)
    protected String naziv;

    @Column(name = "opis", unique = false, nullable = true)
    protected String opis;

    @Column(name = "cena", unique = false, nullable = false)
    protected double cena;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    @ManyToMany(mappedBy = "uslugaList")
    @JsonIgnore
    protected List<Smestaj> smestajList = new ArrayList<>();

    @ManyToMany(mappedBy = "uslugaList")
    private
    List<Category> categoryList = new ArrayList<>();


    public List<Smestaj> getSmestaj() {
        return smestajList;
    }

    public void setSmestaj(List<Smestaj> smestaj) {
        this.smestajList = smestaj;
    }

    public String getNaziv() {
        return naziv;
    }

    public void setNaziv(String value) {
        this.naziv = value;
    }

    public String getOpis() {
        return opis;
    }

    public void setOpis(String value) {
        this.opis = value;
    }

    public double getCena() {
        return cena;
    }

    public void setCena(double value) {
        this.cena = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long value) {
        this.id = value;
    }


    public List<Category> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(List<Category> categoryList) {
        this.categoryList = categoryList;
    }
}
