
package com.megatravel.agentback.xml.dto;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.2
 * 2019-06-30T02:31:30.587+02:00
 * Generated source version: 2.7.2
 */

@WebFault(name = "SOAPException", targetNamespace = "http://service.agent.megatravel.com/")
public class SOAPException_Exception extends Exception {
    
    private SOAPException soapException;

    public SOAPException_Exception() {
        super();
    }
    
    public SOAPException_Exception(String message) {
        super(message);
    }
    
    public SOAPException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SOAPException_Exception(String message, SOAPException soapException) {
        super(message);
        this.soapException = soapException;
    }

    public SOAPException_Exception(String message, SOAPException soapException, Throwable cause) {
        super(message, cause);
        this.soapException = soapException;
    }

    public SOAPException getFaultInfo() {
        return this.soapException;
    }
}
